---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: grade-tracker
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 5003
  selector:
    app: analytics-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: grade-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: lcausing/grade_tracker-analytics-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: FLASK_ENV
              value: "production"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_URI
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /analytics
              port: 5003
            initialDelaySeconds: 20
            periodSeconds: 10
