---
apiVersion: v1
kind: Namespace
metadata:
  name: grade-tracker
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: grade-tracker
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: apppass
  JWT_SECRET: 7f9a4c62b93f24ad9c6e4a91f3d94b12a!
  MONGO_URI: mongodb://mongodb:27017/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: grade-tracker
data:
  MYSQL_DATABASE: grade_tracker
  MYSQL_USER: appuser
