---
apiVersion: v1
kind: Service
metadata:
  name: show-results
  namespace: grade-tracker
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: show-results
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results
  namespace: grade-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: show-results
  template:
    metadata:
      labels:
        app: show-results
    spec:
      containers:
        - name: show-results
          image: grade_tracker-show-results:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: ANALYTICS_SERVICE_URL
              value: http://analytics-service:5003
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 20
            periodSeconds: 10
